import { EmbedBuilder } from "discord.js";
export function formatForTwitch(loadout) {
  const equipmentString = loadout.equipment.join(", ");
  return `🎲 Class: ${loadout.className} | Spec: ${loadout.ability} | Weapon: ${loadout.weapon} | Equipment: ${equipmentString}`;
}

export function formatForDiscord(loadout) {
  const embed = new EmbedBuilder()
    .setColor(0xffd700)
    .setTitle("🎲 Random Loadout")
    .addFields(
      { name: "Class", value: loadout.className, inline: true },
      { name: "Spec", value: loadout.ability, inline: true },
      { name: "Weapon", value: loadout.weapon, inline: true },
      { name: "Equipment", value: loadout.equipment.join(", "), inline: false }
    )
    .setFooter({ text: "Generated by Vibebot" });
  return embed;
}
